title: 'CalConnect: The Calendaring and Scheduling Consortium'
email: info@calconnect.org
description: >-
  CalConnect is the standards development organization for vendors and users of
  collaboration systems and tools, in particular calendaring and scheduling.

# domain: # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://calconnect.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /calconnect.org # place folder name if the site is served in a subfolder

twitter_username: CalConnect
github_username:  CalConnect

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

collections:
  events:
    output: true
  resources:
    output: true
  membership_pages:
    output: true
    permalink: /membership/:title
  about_pages:
    output: true
    permalink: /about/:title
  news_pages:
    output: true
    permalink: /news/:title
  event_pages:
    output: true
    permalink: /events/:title
  posts:
    output: true
    permalink: /news/:year-:month-:day-:title/
  pages:
    output: true
    permalink: //:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - old/

jekyll-archives:
  enabled: [ categories ]
  layout: category
  permalinks:
    category: /news/:name/